version: "3"
services:
  database:
    image: postgres:14
    environment:
      - "POSTGRES_USER=admin"
      - "POSTGRES_PASSWORD=password"
      - "POSTGRES_DB=TodoDB"
    volumes:
       - postgres-db:/data/postgres
    ports:
      - "5432:5432"
volumes:
  postgres-db:
    driver: local